name: "check my bundlephobia"
on: pull_request

jobs:
  bundlecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: GitHub Action for JS Bundle Size
        uses: carlesnunez/check-my-bundlephobia@v1.2.0
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            strict: true
            threshold: 500
